baseURL = "https://david-salazar.github.io/"
publishDir = "../../David-Salazar.github.io"
languageCode = "en-us"
title = "Dilettanting Data Science"
theme = "hugo-lithium"
googleAnalytics = ""
disqusShortname = "https-david-salazar-github-io"
ignoreFiles = ["\\.Rmd$", "\\.Rmarkdown$", "_files$", "_cache$"]

[permalinks]
    post = "/:year/:month/:day/:slug/"
    
[[menu.main]]
    name = "Posts"
    url = "https://david-salazar.github.io/"

[[menu.main]]
    name = "About"
    url = "/about/"
[[menu.main]]
    name = "GitHub"
    url = "https://github.com/David-Salazar"
[[menu.main]]
    name = "Twitter"
    url = ""

[params]
    description = "A website built through Hugo and blogdown."

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.11.0"
    highlightjsCDN = "//cdn.bootcss.com"
    highlightjsLang = ["r", "yaml", "python"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdn.bootcss.com"
    MathJaxVersion = "2.7.1"

[params.logo]
    url = "turner.jpg"
    width = 200
    height = 200
    alt = "Logo"


